# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Build and Publish CommHandler

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/commhandler-ci.yaml'
      - 'CommHandler/**'

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SGrJava
        uses: actions/checkout@v4
        with:
          ref: ${{github.ref}}
          fetch-tags: true
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build SGrJava CommHandler
        working-directory: CommHandler
        run: |
          chmod +x ./gradlew
          ./gradlew clean build --no-daemon

      - name: Publish SGrJava CommHandler
        # publish after committing to master or creating tag commhandler-{version}
        if: success() && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/commhandler-'))
        working-directory: CommHandler
        run: |
          chmod +x ./gradlew
          ./gradlew publishMavenJavaPublicationToNexusRepository -Pnexus.username=smartgrid -Pnexus.password=${{ secrets.NEXUS_PASSWORD }} --no-daemon
      
      - name: Build Javadoc
        working-directory: CommHandler
        run: |
          chmod +x ./gradlew
          ./gradlew javadoc

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # Change this if using a different branch
          folder: build/docs/javadoc  # Path where Javadoc is generated
          target-folder: commhandler
