name: Build and Publish CommHandler
on:
  workflow_dispatch:
  push:
    branches: [ '**' ]
    paths: [ 'CommHandler/**' ]

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SGrJava
        uses: actions/checkout@v4
        with:
          ref: ${{github.ref}}
          fetch-tags: true
          fetch-depth: 0

      - name: Build and Publish SGrJava CommHandler
        working-directory: CommHandler
        run: |
          chmod +x ./gradlew
          ./gradlew clean build publishMavenJavaPublicationToNexusRepository -Pnexus.username=smartgrid -Pnexus.password=${{ secrets.NEXUS_PASSWORD }} --no-daemon
