# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Build and Publish CommHandler

on:
  workflow_dispatch:
  push:
    paths: [ 'CommHandler/**' ]

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SGrJava
        uses: actions/checkout@v4
        with:
          ref: ${{github.ref}}
          fetch-tags: true
          fetch-depth: 0

      - name: Build SGrJava CommHandler
        working-directory: CommHandler
        run: |
          chmod +x ./gradlew
          ./gradlew clean build --no-daemon

      - name: Publish SGrJava CommHandler
        # publish after committing to master or creating tag commhandler-{version}
        if: success() && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/commhandler-'))
        working-directory: CommHandler
        run: |
          chmod +x ./gradlew
          ./gradlew publishMavenJavaPublicationToNexusRepository -Pnexus.username=smartgrid -Pnexus.password=${{ secrets.NEXUS_PASSWORD }} --no-daemon
